#!/bin/sh
#
# This script grows data FS on iSCSI disk
#
iscsiadm -m session --rescan
mpath_dev=`blkid --label datafs | sed -n "s/^\/dev\/mapper\/\([0-9a-f]*\)\(p1\)*.*/\1/p"`
multipathd -k"resize map $mpath_dev"
xfs_growfs /dev/mapper/$mpath_dev
