#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

cp -f /usr/lib/python3/dist-packages/cloudinit/net/cmdline.py /usr/lib/python3/dist-packages/cloudinit/net/cmdline.py.ORIG
mv -f /usr/lib/python3/dist-packages/cloudinit/net/cmdline.py.UPDATED /usr/lib/python3/dist-packages/cloudinit/net/cmdline.py
cp -f /usr/lib/python3/dist-packages/cloudinit/net/netplan.py /usr/lib/python3/dist-packages/cloudinit/net/netplan.py.ORIG
mv -f /usr/lib/python3/dist-packages/cloudinit/net/netplan.py.UPDATED /usr/lib/python3/dist-packages/cloudinit/net/netplan.py
