#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

cat <<EOF > /etc/sysctl.d/99-tuning.conf
# Settings for Kubernetes
vm.overcommit_memory=1
vm.panic_on_oom=0
vm.max_map_count=262144
kernel.panic=10
kernel.panic_on_oops=1
kernel.keys.root_maxbytes=25000000
kernel.sched_autogroup_enabled=0

# Disabling IPv6
net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.default.disable_ipv6=1
net.ipv6.conf.lo.disable_ipv6=1

# Network performance
net.core.rmem_default=25165824
net.core.wmem_default=25165824
net.core.rmem_max=25165824
net.core.wmem_max=25165824
net.core.optmem_max = 40960
net.ipv4.tcp_rmem=20480 12582912 25165824
net.ipv4.tcp_wmem=20480 12582912 25165824
net.core.netdev_max_backlog=250000
EOF
