#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Dig up the kernel to use
KERNEL=$(basename $(ls -1rv /boot/vmlinu*generic 2>/dev/null || ls -1rv /boot/vmlinu* | head -1) | sed "s/vmlinuz-\(.*\)/\1/")

# Install kernel headers
apt-get -y install linux-headers-${KERNEL}
