#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

apt-get -y purge snapd
apt -y remove accountsservice
apt -y remove unattended-upgrades
systemctl stop systemd-timesyncd.service
systemctl disable systemd-timesyncd.service
