#!/bin/sh

echo -n "Verifying cpufreq/scaling_governor setting..."
scaling_governor=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`
if [ "${scaling_governor}" = "performance" ]; then
    echo "passed"
else
    echo "failed"
    echo "Expected scaling_governor set to 'performance', actual is '${scaling_governor}'!"
    return 1
fi
return 0
