#!/bin/sh

echo -n "Verifying if chrony is synchronized..."
leap_status=`chronyc tracking | sed -n "s/^Leap status[^:]*:[^a-zA-Z]*\([a-zA-Z]*\).*/\1/p"`
if [ "${leap_status}" = "Normal" ]; then
    echo "passed"
else
    echo "failed"
    echo "Expected leap status as 'Normal', actual is '${leap_status}'!"
    return 1
fi
return 0
