#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

apt-get -y purge snapd
apt-get -y purge modemmanager
apt-get -y purge packagekit
apt-get -y purge open-vm-tools
apt-get -y autoremove  open-vm-tools
apt-get -y purge accountsservice
apt-get -y autoremove accountsservice
apt-get -y purge unattended-upgrades
systemctl stop systemd-timesyncd.service
systemctl disable systemd-timesyncd.service
